// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjr2U-qTdMe1E9JQipfSNka8GXeIq85ok',
    appId: '1:749886344103:web:ff181aaa010e7626670482',
    messagingSenderId: '749886344103',
    projectId: 'duka-letu-58a6f',
    authDomain: 'duka-letu-58a6f.firebaseapp.com',
    storageBucket: 'duka-letu-58a6f.firebasestorage.app',
    measurementId: 'G-M7VMDZGKBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCxC-YvK6MeRvccgLOGpY3qkxfL5y6-y4',
    appId: '1:749886344103:android:f5756a85a1d9de8f670482',
    messagingSenderId: '749886344103',
    projectId: 'duka-letu-58a6f',
    storageBucket: 'duka-letu-58a6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFxM5gLGDfxtli4UGY9sQz8bjh0ZXliwk',
    appId: '1:749886344103:ios:c39810a42690e130670482',
    messagingSenderId: '749886344103',
    projectId: 'duka-letu-58a6f',
    storageBucket: 'duka-letu-58a6f.firebasestorage.app',
    iosBundleId: 'com.example.ecomerceClassApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFxM5gLGDfxtli4UGY9sQz8bjh0ZXliwk',
    appId: '1:749886344103:ios:c39810a42690e130670482',
    messagingSenderId: '749886344103',
    projectId: 'duka-letu-58a6f',
    storageBucket: 'duka-letu-58a6f.firebasestorage.app',
    iosBundleId: 'com.example.ecomerceClassApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjr2U-qTdMe1E9JQipfSNka8GXeIq85ok',
    appId: '1:749886344103:web:c50bf344154e388a670482',
    messagingSenderId: '749886344103',
    projectId: 'duka-letu-58a6f',
    authDomain: 'duka-letu-58a6f.firebaseapp.com',
    storageBucket: 'duka-letu-58a6f.firebasestorage.app',
    measurementId: 'G-HJHCEN7VZL',
  );
}
